/**
 * @license
 * Copyright 2026 Easy Code team
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Built-in workflow templates.
 *
 * These are pre-written orchestration scripts that the AI can invoke by `name`
 * instead of handwriting a full JS script. The AI only needs to supply `args`
 * (a structured JSON object), dramatically lowering the barrier.
 *
 * Registry pattern: `getBuiltin(name)` → returns the script template as a string,
 * with `args` injected as a top-level `const args = {...}`.
 */

/** A single task in the batch-parallel workflow. */
export interface BatchTask {
  /** The instruction/prompt for this sub-agent. */
  prompt: string;
  /** Short label for UI display. */
  label?: string;
  /** Slug-friendly name for the worktree branch (e.g. "fix-login"). */
  name?: string;
}

/** Args accepted by the batch-parallel workflow. */
export interface BatchParallelArgs {
  tasks: BatchTask[];
}

// ─── Builtin registry ────────────────────────────────────────────────────────

/** Metadata for a built-in workflow. */
export interface BuiltinWorkflowMeta {
  name: string;
  description: string;
  /** Whether this workflow should auto-enable worktree isolation. */
  autoWorktree: boolean;
}

/** Registry of available built-in workflows. */
const REGISTRY: Record<string, BuiltinWorkflowMeta> = {
  'batch-parallel': {
    name: 'batch-parallel',
    description:
      'Run multiple independent tasks in parallel, each in its own isolated git worktree. ' +
      'Perfect for processing a list of requirements/changes from a document.',
    autoWorktree: true,
  },
};

/** List all available built-in workflow names. */
export function listBuiltinWorkflows(): string[] {
  return Object.keys(REGISTRY);
}

/** Check if a name refers to a known built-in workflow. */
export function isBuiltinWorkflow(name: string): boolean {
  return name in REGISTRY;
}

/** Get metadata for a built-in workflow. */
export function getBuiltinMeta(name: string): BuiltinWorkflowMeta | undefined {
  return REGISTRY[name];
}

/**
 * Resolve a built-in workflow name + args into a runnable script string.
 *
 * The `args` object is JSON-stringified and injected as `const args = {...}`
 * at the top of the script, so the template can read it.
 *
 * Returns `null` if the name is not recognized.
 */
export function resolveBuiltinWorkflow(
  name: string,
  args: unknown,
): { script: string; autoWorktree: boolean } | null {
  const meta = REGISTRY[name];
  if (!meta) return null;

  switch (name) {
    case 'batch-parallel':
      return {
        script: generateBatchParallelScript(args),
        autoWorktree: meta.autoWorktree,
      };
    default:
      return null;
  }
}

// ─── batch-parallel template ─────────────────────────────────────────────────

/**
 * Generate the batch-parallel workflow script.
 *
 * The script:
 * 1. Reads `args.tasks` (injected as a const)
 * 2. Calls `agent.runParallel([...])` with worktree isolation on each task
 * 3. Collects results and returns a JSON summary
 *
 * Args shape: { tasks: [{ prompt, label?, name? }] }
 */
function generateBatchParallelScript(args: unknown): string {
  // Safe JSON injection — JSON.stringify handles all escaping
  const argsJson = JSON.stringify(args ?? { tasks: [] });

  return `// ─── Auto-generated by builtin workflow: batch-parallel ───
const args = ${argsJson};

export const meta = {
  name: 'batch-parallel',
  description: '并行处理 ' + (args.tasks || []).length + ' 个独立任务（worktree 隔离）',
  phases: [
    { title: '并行执行', detail: '所有任务同时在独立 worktree 中运行' },
    { title: '汇总结果', detail: '收集各任务成果并生成报告' },
  ],
};

export default async function(agent) {
  phase('并行执行');

  const tasks = (args.tasks || []).map((t, i) => ({
    prompt: t.prompt,
    label: t.label || ('task-' + (i + 1)),
    worktreeName: t.name || t.label || ('task-' + (i + 1)),
    worktree: true,
    max_turns: 30,
  }));

  if (tasks.length === 0) {
    return 'No tasks provided. Pass args.tasks = [{ prompt, label? }] to run.';
  }

  const results = await agent.runParallel(tasks);

  phase('汇总结果');

  const summary = results.map((r, i) => {
    const task = tasks[i];
    return {
      task: task.label,
      success: r.success,
      summary: r.success ? (r.result || r.summary || '(no output)') : ('FAILED: ' + (r.error || 'unknown')),
    };
  });

  const succeeded = summary.filter(s => s.success).length;
  const failed = summary.length - succeeded;

  let report = '并行任务完成: ' + succeeded + ' 成功, ' + failed + ' 失败\\n\\n';
  report += summary.map((s, i) => {
    return '### ' + (i + 1) + '. ' + s.task + ' ' + (s.success ? '✅' : '❌') + '\\n' + s.summary;
  }).join('\\n\\n');

  return report;
}
`;
}
